image: python:slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip/


before_script:
  - python -V
  - lscpu
  - pip install -r python-requirements.txt

stages:
  - languages
  - categories
  - threads

test-languages:
  when: manual
  stage: languages
  script:
    - time python start.py languages data/20191101/12/


test-categories:
  when: manual
  stage: categories
  script:
    - time python start.py categories data/20191101/12/


test-threads:
  when: manual
  stage: threads
  script:
    - time python start.py threads data/20191101/12/
