image: python:slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip/


before_script:
  - python -V
  - lscpu
  - pip install -r python-requirements.txt

stages:
  - languages
  - is_news
  - categories
  - threads
  - rankings

test-languages:
  stage: languages
  script:
    - time python start.py languages data/20191101/12/


test-is_news:
  stage: is_news
  script:
    - time python start.py news data/20191101/12/

test-categories:
  stage: categories
  script:
    - time python start.py categories data/20191101/12/

test-threads:
  stage: threads
  script:
    - time python start.py threads data/20191101/12/

test-rankings:
  stage: ranking
  script:
    - time python start.py top data/2019101/12/
