image: python:slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip/

before_script:
  - python -V
  - lscpu
  - pip install -r python-requirements.txt

stages:
  - languages
  - news
  - categories
  - threads
  - top


languages_1101_12:
  stage: languages
  when: always
  script:
    - time python start.py languages data/20191101/12/

languages_1108_18:
  stage: languages
  when: always
  script:
    - time python start.py languages data/20191108/18/

languages_1115_00:
  stage: languages
  when: always
  script:
    - time python start.py languages data/20191115/00/


news_1101_12:
  stage: news
  when: always
  script:
    - time python start.py news data/20191101/12/

news_1108_18:
  stage: news
  when: always
  script:
    - time python start.py news data/20191108/18/

news_1115_00:
  stage: news
  when: always
  script:
    - time python start.py news data/20191115/00/


categories_1101_12:
  stage: categories
  when: always
  script:
    - time python start.py categories data/20191101/12/

categories_1108_18:
  stage: categories
  when: always
  script:
    - time python start.py categories data/20191108/18/

categories_1115_00:
  stage: categories
  when: always
  script:
    - time python start.py categories data/20191115/00/


threads_1101_12:
  stage: threads
  when: always
  script:
    - time python start.py threads data/20191101/12/

threads_1108_18:
  stage: threads
  when: always
  script:
    - time python start.py threads data/20191108/18/

threads_1115_00:
  stage: threads
  when: always
  script:
    - time python start.py threads data/20191115/00/


top_1101_12:
  stage: top
  when: always
  script:
    - time python start.py top data/20191101/12/

top_1108_18:
  stage: top
  when: always
  script:
    - time python start.py top data/20191108/18/

top_1115_00:
  stage: top
  when: always
  script:
    - time python start.py top data/20191115/00/
